version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: pg-delta
    environment:
      POSTGRES_USER: delta
      POSTGRES_PASSWORD: delta
      POSTGRES_DB: delta
    ports:
      - "5432:5432"
    volumes:
      # 注意这里：去掉了末尾的 /data
      - pg_delta_data:/var/lib/postgresql
    restart: always

volumes:
  pg_delta_data: